//This is the js for the level editor

//Canvas stuff
var c = document.getElementById("mainCanvas");
var ctx = c.getContext("2d");
c.height = window.innerWidth / 2;
c.width = window.innerWidth;
var s = c.width;

//Mouse coords
var mx = 0;
var my = 0;

//String for code generated by the level editor
var level = "";

var rectangle = "";

var rectangleX = 0;
var rectangleY = 0;

ctx.fillRect(0, 0, s / 2, s / 2);

//Player placeholders for reference
var p1Reference = {
    x: s / 4,
    y: s / 2,
    size: 0.025 * s,
    draw: function(){
            ctx.fillStyle = "blue";
            ctx.fillRect(this.x - (this.size / 2), this.y -this. size, this.size, this.size);
    }
}
var p2Reference = {
    x: 3 * s / 4,
    y: s / 2,
    size: 0.025 * s,
    draw: function(){
            ctx.fillStyle = "blue";
            ctx.fillRect(this.x - (this.size / 2), this.y -this. size, this.size, this.size);
    }
}

p1Reference.draw();
p2Reference.draw();

onmousemove = function(e){
    mx = e.clientX;
    my = e.clientY;
}

onkeydown = function(e){

    //L
    if(e.which == 76){
        level += "new LightSource(" + mx / s + " * s," + my / s + " * s);\n";
        ctx.fillStyle = "white";
        if(mx > s / 2){
            ctx.fillStyle = "black";
        }
        ctx.beginPath();
        ctx.arc(mx, my, s * 0.01, 0, 2 * Math.PI);
        ctx.fill();
        ctx.closePath();
    }

    //p
    if(e.which == 80){
        if(rectangle == ""){
            rectangle += "new PlatformNormal(" + mx / s + " * s, " + my / s + " * s, ";
            rectangleY = my / s;
            rectangleX = mx / s;
        } else {
            rectangle += "" + -(rectangleX - (mx / s)) + " * s, " + -(rectangleY- (my / s)) + " * s);\n";
            level += rectangle;
            rectangle = "";
            ctx.fillStyle = "white";
            if(mx > s / 2){
                ctx.fillStyle = "black";
            }
            ctx.fillRect((rectangleX * s), rectangleY * s, -((rectangleX * s) - mx), -((rectangleY * s) - my));
        }
    }
}